# Generated by Django 4.2.5 on 2023-10-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stazi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='winner_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stazi_app.user'),
        ),
    ]
