# Generated by Django 4.2.5 on 2023-10-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stazi_app', '0002_alter_auction_winner_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='timestamp',
        ),
    ]
